### ISSUE TITLE
grep error before screenfetch layout

### ISSUE THREAD

**Issue by hikikomori4** [KittyKatt/screenFetch#788] opened 2024-03-31 12:03 UTC
Every time run program under a tmux session, a grep error appears. Two lines:
```
grep: warning: stray \ before "
grep: warning: stray \ before "
```
There is no error when running without tmux. grep alone or other programs do not give errors.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] new distro request
```

**Bug report**
```
 => Show us the output of: screenfetch -v
```

```
$ screenfetch -v
:: Finding distro...found as 'Manjaro 23.1.3'
:: Finding hostname and user...found as 'user@host'
:: Finding kernel version...found as 'x86_64 Linux 6.5.13-7-MANJARO'
:: Finding current uptime...found as '1d 7h 28m'
:: Finding current package count...found as '1591'
:: Finding current shell...found as 'bash'
:: Finding current resolution(s)...found as '2560x1024'
grep: предупреждение: лишняя \ перед "
grep: предупреждение: лишняя \ перед "
:: Finding desktop environment...found as 'Not Present'
:: Finding window manager...found as 'KWin'
:: Finding window manager theme...found as 'Not Found'
:: Finding GTK2 theme...found as 'Breeze'
:: Finding GTK3 theme...found as 'Breeze'
:: Finding icon theme...found as 'breeze'
:: Finding user font...found as 'Noto Sans,  10'
:: Finding current CPU...found as 'Intel Core i3-2120 @ 4x 3.3GHz [51.0°C]'
:: Finding current disk usage...found as '7,8T / 14T (57%%)'
:: Finding current GPU...found as 'Mesa Intel(R) HD Graphics 2000 (SNB GT1)'
:: Finding current RAM usage...found as '3363MiB / 3643MiB'

 ██████████████████  ████████     user@host
 ██████████████████  ████████     OS: Manjaro 23.1.3 Vulcan
 ██████████████████  ████████     Kernel: x86_64 Linux 6.5.13-7-MANJARO
 ██████████████████  ████████     Uptime: 1d 7h 28m
 ████████            ████████     Packages: 1591
 ████████  ████████  ████████     Shell: bash
 ████████  ████████  ████████     Resolution: 2560x1024
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze
 ████████  ████████  ████████     Font: Noto Sans,  10
 ████████  ████████  ████████     Disk: 7,8T / 14T (57%)
 ████████  ████████  ████████     CPU: Intel Core i3-2120 @ 4x 3.3GHz [51.0°C]
 ████████  ████████  ████████     GPU: Mesa Intel(R) HD Graphics 2000 (SNB GT1)
                                  RAM: 3363MiB / 3643MiB

```

**New distro request**
```
Distro name:
Homepage:
Distro logo:
Package manager:

Show us the output of
 => lsb_release -sirc
ManjaroLinux 23.1.3 Vulcan

 => cat /etc/os-release

NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

 => ls -1 /etc/*-release

/etc/arch-release
/etc/lsb-release
/etc/manjaro-release
/etc/os-release

```

**Comment by MFTabriz** [comment] 2024-04-06 19:16
seems like a duplicate of #754

**Comment by mohemiv** [comment] 2024-04-22 11:13
I can reproduce the issue in 3.9.1, but I the issue doesn't appear in screenfetch-dev (master branch).

**Comment by nPHYN1T3** [comment] 2024-05-03 23:43
Seeing this here as well.

**Comment by shroomwastaken** [comment] 2024-05-07 12:05
seeing this as well
just installed with
`sudo pacman -Syu screenfetch`

**Comment by ogaken-1** [comment] 2024-06-25 12:40
#755 will resolve this. It's not released still now.

**Comment by Dakoteus** [comment] 2024-12-03 04:17
I'm running Nixos Unstable, 3.9.1 and getting this issue no matter what terminal or shell I use

**Comment by Dakoteus** [comment] 2024-12-03 04:53
Yes, #755 resolves this. Still hasn't been released though.

**Closed** 2024-12-03 07:29 UTC

**Comment by Dakoteus** [comment] 2024-12-04 02:11
@KittyKatt yayy, no problem! thank you.
