### ISSUE TITLE
Syntax invalid

### ISSUE THREAD

**Issue by OXEDAN1337** [KittyKatt/screenFetch#535] opened 2017-12-07 12:08 UTC
I'm running FreeBSD 9.3
root@root599745:~ # sh screenfetch-dev
system: 47: Syntax error: word unexpected (expecting ")")

root@root599745:~ # python screenfetch-dev
  File "screenfetch-dev", line 47
    valid_display=( distro host kernel uptime pkgs shell res de wm wmtheme gtk disk cpu gpu mem )
                              ^
SyntaxError: invalid syntax

How can i fix?

**Comment by darealshinji** [comment] 2017-12-07 12:20
You need to run it with bash, not sh. You also need fdescfs(5) and procfs(5) to be mounted.

**Comment by darealshinji** [comment] 2018-06-02 15:13
@OXEDAN1337 Does it run if you use bash(1) and have fdescfs(5) and procfs(5) mounted like I said?

**Comment by jhelfman** [comment] 2019-08-09 23:44
I maintain the port for screenfetch for FreeBSD. It does not need procfs, unless this is being supplied another way, or perhaps there is something that isn't being reported by not using it. I can confirm that fdescfs is mounted for me, but don't know what would happen if it wasn't mounted and I ran the script.

It works with bash without issue.

**Comment by jhelfman** [comment] 2019-08-20 20:07
> I'm running FreeBSD 9.3
> root@root599745:~ # sh screenfetch-dev
> system: 47: Syntax error: word unexpected (expecting ")")
> 
> root@root599745:~ # python screenfetch-dev
> File "screenfetch-dev", line 47
> valid_display=( distro host kernel uptime pkgs shell res de wm wmtheme gtk disk cpu gpu mem )
> ^
> SyntaxError: invalid syntax
> 
> How can i fix?

@OXEDAN1337 I'm not sure of what version of FreeBSD you are running now, however as of today version 9.3 is no longer supported. https://www.freebsd.org/security/security.html#sup

**Comment by darealshinji** [comment] 2019-08-22 11:51
Closing it because user didn't answer after 2 years, FreeBSD 9.3 is outdated now and the script needs to be run with bash not sh or python.

**Closed by darealshinji** 2019-08-22 11:51 UTC
Labels: bug
