### ISSUE TITLE
Add support for KDE neon

### ISSUE THREAD

**Issue by virtualdemon** [KittyKatt/screenFetch#541] opened 2018-01-17 20:24 UTC
#126 
WebSite : https://neon.kde.org/
Logo : [GoogleImageSearch](https://www.google.nl/search?q=kde+neon+logo&client=firefox-b-ab&dcr=0&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjj39rE3N_YAhWHY1AKHV-4CcsQsAQIKA&biw=1024&bih=622#imgrc=pEvqm-t5go0mJM:) &  [Wikimedia](https://commons.wikimedia.org/wiki/File:Neon-logo.svg)
Ascii logo : [LOGO](https://raw.githubusercontent.com/dylanaraps/neofetch/master/ascii/distro/kde) from : [Dylan Araps](https://github.com/dylanaraps)
## Distro info : **cat /etc/os-release**
NAME="KDE neon"
VERSION="5.11"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.11"
VERSION_ID="16.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

## The picture from _screenfetch_ output 
![Uploading image_2018-01-17_23-48-35.png…](Click!)
or
[image_on_Imgur](https://imgur.com/a/uj13Z)

## manual installation : 
**wget -O screenfetch https://git.io/vaHfR
chmod +x screenfetch
./screenfetch**

i have this output : 
![Uploading image.png…](Click!)
or
[image_on_Imgur](https://imgur.com/a/kAD1E)

**Comment by Xmetalfanx** [comment] 2018-03-28 03:04
This is fixed already, but not in the release offered by default via Neon/ 16.04 ... I am on Neon and was actually going to try to add the code myself when i noticed it's already there 

by adding the PPA listed in the README section I can confirm that this updated version has the fix for Neon `screenfetch/xenial,xenial 3.8.0-3~xenial all [upgradable from: 3.7.0-1]` is exactly what was upgraded 

https://github.com/KittyKatt/screenFetch/commit/ac048b4277ec82e5a22eb9f6babe41abbccd42d5 and commits right after are the commits that added the support.   

Adding "details" for the devs so they can close this and have one less "issue" listed 

those screenshots PRE-PPA addition/version upgrade IS what I saw on my updated copy of Neon

**Comment by darealshinji** [comment] 2018-03-28 13:20
Closing, since Neon is already supported.

**Closed by darealshinji** 2018-03-28 13:20 UTC
