### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by candrews** [KittyKatt/screenFetch#445] opened 2017-03-03 13:55 UTC
There have been quite a few changes since the last release which is 3.7.0: https://github.com/KittyKatt/screenFetch/compare/v3.7.0...master

Can you please create a new release?

Thanks!

**Comment by darealshinji** [comment] 2017-03-03 14:58
Closing, as it's a duplicate of https://github.com/KittyKatt/screenFetch/issues/436

**Closed by darealshinji** 2017-03-03 14:58 UTC
